### ISSUE TITLE
〔 Comments Section 〕Fallout Shelter Online: Attachments and Remaking

### ISSUE THREAD

**Issue by morgosus** [morgosus/comments.morgosus.github.io#5]
A comments section for the [Fallout Shelter Online: Attachments and Remaking](https://www.toms.click/gaming/foso/2021/08/13/fallout-shelter-attachments.html) post.

**Comment by GHex06** [comment]
A more comprehensive guide in crafting attachments and it's connection to the Mystery treasure will greatly improve the post :)

**Comment by morgosus** [comment]
> A more comprehensive guide in crafting attachments and it's connection to the Mystery treasure will greatly improve the post :)

The next one will most likely be all about the Mystery Treasure.
